services:
  postgres:
    image: postgres:17
    container_name: alpha-engine-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: alpha
      POSTGRES_PASSWORD: alpha
      POSTGRES_DB: alpha_engine

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: