"""add creator to tokens

Revision ID: 166336e349c8
Revises: 10519a530de2
Create Date: 2026-08-06 15:33:08.044272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166336e349c8'
down_revision: Union[str, Sequence[str], None] = '10519a530de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_creator'), 'tokens', ['creator'], unique=False)
    op.drop_column('tokens', 'first_seen_tx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('first_seen_tx', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tokens_creator'), table_name='tokens')
    # ### end Alembic commands ###
