"""add token metadata fields

Revision ID: e3ec9c7d5d64
Revises: bf2fbf672090
Create Date: 2026-08-06 15:22:06.687120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ec9c7d5d64'
down_revision: Union[str, Sequence[str], None] = 'bf2fbf672090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('creator', sa.String(length=64), nullable=True))
    op.add_column('tokens', sa.Column('decimals', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('supply', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('first_seen_tx', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'first_seen_tx')
    op.drop_column('tokens', 'supply')
    op.drop_column('tokens', 'decimals')
    op.drop_column('tokens', 'creator')
    # ### end Alembic commands ###
